const char WIFI_SSID[] = "chariot-guest";
const char WIFI_PASS[] = "Chariot.403jfk.Guest";

const char MQTT_BROKER[] = "a39ag3gh9hkdcb-ats.iot.us-east-1.amazonaws.com";

const char CERTIFICATE[] = R"(
-----BEGIN CERTIFICATE-----
MIICjTCCAXWgAwIBAgIUStAEtyFJiFHXifsI67UR0v+6WGswDQYJKoZIhvcNAQEL
BQAwTTFLMEkGA1UECwxCQW1hem9uIFdlYiBTZXJ2aWNlcyBPPUFtYXpvbi5jb20g
SW5jLiBMPVNlYXR0bGUgU1Q9V2FzaGluZ3RvbiBDPVVTMB4XDTIwMDMwODIxMjA0
M1oXDTQ5MTIzMTIzNTk1OVowHTEbMBkGA1UEAxMSMDEyM0M2MzgyRjQ5RDkzOEVF
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEvBejrN+t9VTq83anfUksHHYk7RiK
ZiIcaLCNyZCiYztGhwB/DIe7u3ik9Qw2XPKwQvWB6HuUze6sR9YQI89hf6NgMF4w
HwYDVR0jBBgwFoAUSN8dNnjQC9BsqNW+tdb+xRMc/NkwHQYDVR0OBBYEFOtRkS/4
JmARWVJzhgC4DoDZ/qNyMAwGA1UdEwEB/wQCMAAwDgYDVR0PAQH/BAQDAgeAMA0G
CSqGSIb3DQEBCwUAA4IBAQBOfTTVLbkqXtu4gvT90K9tJtbDQNt3+S29rLnIgjlW
A9YGpDUAp/WF7HTAkdSOLfJ/XKj+c210XGgNRgwwJjSQvugVohp4x5SonPCV8KOy
bzQHVUS783BWHRZC/9F3wvrfebl2EDL+xsMfxeI8BInO3CH8o1PbzMQykEtvrzda
sPEf+YaZuyDqYB6ukywL/TxhM+5qyk/FksmflcLoMj/UYkoiMVMZWU7vrrcjpTcj
ZpKfAERZ9eOicS2yB05jrZ25DdGXT/FOYqBQx0M9aSBSqJnLl5a42Elx8ZGTdn/I
rGG4y9wRKEdJzmLIssg3EcA3hspmonoSelYBU/4ANnEN
-----END CERTIFICATE-----
)";
